system: "You are a helpful assistant. Your task is to extract relevant information from provided documents. For each sentence in your response, you need to cite back to the original document identifier, such as [1]."
user: f"Background:\n{docs}\n\nQuestion:\ {question}"
system_without_docs: "You are a helpful assistant. Answer the questions as short as possible."
user_without_docs: f"Question:\ {question}"
example: false