retrieve_top_k: 50
rerank_top_k: 50
generation_top_k: 20
pyserini_num_threads: 2
run_name: null
dataset_folder: datasets/
index_folder: indexes/
runs_folder: runs/
experiments_folder: trec_rag_test_2024/baseline_70b_filtered/plain
processing_num_proc: 2
retriever:
  init_args:
    _target_: models.retrievers.custom.CUSTOM
    model_name: custom_baseline_blender_70b_filtered
generator:
  init_args:
    _target_: models.generators.vllm.LLM
    model_name: meta-llama/Meta-Llama-3.1-70B-Instruct
    max_new_tokens: 512
    max_length: 100000
    quantization: bitsandbytes
  batch_size: 12
dataset:
  train:
    doc: null
    query: null
  dev:
    doc:
      init_args:
        _target_: modules.dataset_processor.MSMARCOV21SEG
        split: full
    query:
      init_args:
        _target_: modules.dataset_processor.TrecRAGTestQueries
        split: test
  test:
    doc: null
    query: null
prompt:
  system: 'You are a concise and research-focused assistant. Provide brief, single-paragraph
    answers for the Question that start immediately with specific, evidence-based
    information. Answer the Question by directly presenting scientifically supported
    facts in a concise manner using only information exclusively from the Documents(some
    maybe irrelevant), contained within a single paragraph. Every sentence must be
    brief, contain specific, evidence-based information, and directly address the
    question. Begin immediately with factual content, avoiding any introductory phrases,
    affirmations, or conversational language. '
  user: f"Question:\ {question} \n\nDocuments:\n{docs}"
  system_without_docs: Given the Question below, provide an answer for the Question.
    Strive to generate a longer text, and ensure that your response is coherent, fluent
    and comprehensive with respect to the Question.
  user_without_docs: f"Question:\ {question}"
  example: false
