init_args: 
  _target_: models.retrievers.dense.Dense
  model_name: "facebook/contriever-msmarco"
  max_len: 256
  pooler:
    _target_: models.retrievers.dense.MeanPooler
  similarity: 
    _target_: models.retrievers.dense.DotProduct
batch_size: 464