generate_test_samples: 10
test_size_ratio: 0.0005
trainer:
  dataloader_num_workers: 8
  eval_accumulation_steps: 2
  gradient_accumulation_steps: 2
  num_train_epochs: 2
  weight_decay: 0.1
  warmup_ratio: 0.05
  learning_rate: 5e-5
  per_device_train_batch_size: 12
  per_device_eval_batch_size: 12
  bf16: True
  report_to: "wandb"