generate_test_samples: 5
test_size_ratio: 0.0005
trainer:
  dataloader_num_workers: 12
  eval_accumulation_steps: 1
  gradient_accumulation_steps: 1
  num_train_epochs: 2
  weight_decay: 0.1
  warmup_ratio: 0.05
  learning_rate: 1e-4
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 4
  bf16: True
  report_to: "wandb"
lora: 
  lora_alpha: 64
  lora_dropout: 0.1
  r: 32
  bias: "none"
  task_type: "CAUSAL_LM"
