train:
    doc: null
    query: null
dev:
    doc:
        init_args:
            _target_: modules.dataset_processor.PubMed2023
            split: "train"
    query:
        init_args:
            _target_: modules.dataset_processor.TrecBioGen2024Queries
            split: "validation"
test:
    doc: null
    query: null